Update HomeWork-Class3
IntelliJ shows me error:

Error: Could not find or load main class com.company.Main
Caused by: java.lang.ClassNotFoundException: com.company.Main